# SHADOW 
shadow = true;
shadow-radius = 17;        
shadow-offset-x = -10;    
shadow-offset-y = -10;   
shadow-opacity = 0.75;   
shadow-color = "#000000"
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  menu        = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};
# Exclude non-window elements like docks, panels, etc., from shadows
shadow-exclude = [
    "name = 'Polybar'",          
    "class_g = 'Conky'",        
    "class_g = 'Bspwm'",       
    "class_g ?= 'Notification'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];


# GENERAL
backend = "xrender";
experimental-backends = true;
